import {CITIES,CARDS,CHALLENGES,DESTINATIONS,QUEUE_LIMIT,createGame,routeCost,routeStops,routePlan,capacity,demand,findPath,forecast,routeImpact,buildRoute,playCard,endTurn,answerChallenge} from './game.js';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';let state=createGame(),selected=null,plan=null,targetCard=null,sound=false,audio=null;
const name=id=>CITIES.find(c=>c.id===id)?.name||id;
const short=id=>({nyc:'NYC',dc:'DC',phi:'Phila.',bal:'Baltimore',pro:'Providence',har:'Hartford'})[id]||name(id);
const signed=n=>`${n>=0?'+':''}${n}`;
function tone(freq=440){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.start();o.stop(audio.currentTime+.13);}catch{}}
function msg(text){$('message').textContent=text;}
function node(tag,attrs={},text){const el=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,v);if(text)el.textContent=text;return el;}
function render(){
 const f=forecast(state),waiting=Object.values(state.cities).reduce((n,c)=>n+c.queue,0);
 $('season').innerHTML=`${String(state.turn).padStart(2,'0')} <small>/ 24</small>`;$('funds').innerHTML=`${state.funds} <small>funds</small>`;$('score').innerHTML=`${state.score} <small>pts</small>`;
 $('congestion-label').textContent=`${waiting} / ${QUEUE_LIMIT} waiting · ${state.congestion}%`;$('congestion-bar').style.width=state.congestion+'%';$('actions').textContent=`${state.actions} action${state.actions===1?'':'s'} left`;
 $('next').disabled=state.status!=='playing'||state.challenge!==null;$('next').innerHTML=state.turn===24?'Finish railway →':'End season <span>→</span>';
 $('forecast').innerHTML=`<b>This season: ${f.served} arrive · ${f.waiting} still waiting</b><span>${signed(f.income)} funds · tap for why</span>`;
 $('forecast').classList.toggle('danger',f.waiting>=QUEUE_LIMIT||f.income+state.funds<0);
 document.querySelector('.map-key span:last-child').textContent=plan?'Gold = planned stops · green = reused':'+new → destination · orange = full';
 $('routes').replaceChildren();
 state.routes.forEach((r,i)=>{
  const a=CITIES.find(c=>c.id===r.a),b=CITIES.find(c=>c.id===r.b),attrs={x1:a.x,y1:a.y,x2:b.x,y2:b.y};
  const busy=f.lineUsed[i]===r.capacity,highlight=selected&&findPath(state,selected,DESTINATIONS[selected])?.routes.includes(i);
  $('routes').append(node('line',{...attrs,class:'rail-base'}),node('line',{...attrs,class:`rail ${r.express?'express-rail':''} ${busy?'busy-rail':''} ${highlight?'journey-rail':''}`}));
  const hit=node('line',{...attrs,class:'route-hit',role:'button',tabindex:0,'aria-label':`${a.name} to ${b.name}: ${f.lineUsed[i]} of ${r.capacity} seats used this season`});hit.onclick=()=>tapRoute(i);hit.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tapRoute(i);}};$('routes').append(hit);
  if(f.lineUsed[i]>0){const train=node('rect',{x:-5,y:-3,width:10,height:6,rx:2,class:'train'});if(!matchMedia('(prefers-reduced-motion: reduce)').matches)train.append(node('animateMotion',{dur:`${4+i%3}s`,repeatCount:'indefinite',path:`M${a.x},${a.y} L${b.x},${b.y} L${a.x},${a.y}`,rotate:'auto'}));else train.setAttribute('transform',`translate(${(a.x+b.x)/2} ${(a.y+b.y)/2})`);$('routes').append(train);}
 });
 if(selected){const a=CITIES.find(c=>c.id===selected),b=CITIES.find(c=>c.id===DESTINATIONS[selected]);if(!findPath(state,selected,b.id))$('routes').append(node('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'wanted-route'}));}
 if(plan)for(const segment of routePlan(state,...plan).segments){const a=CITIES.find(c=>c.id===segment.a),b=CITIES.find(c=>c.id===segment.b);$('routes').append(node('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:segment.existing?'reused-route':'planned-route'}));}
 $('cities').replaceChildren();const box=$('map').getBoundingClientRect(),verticalFix=(box.width/390)/(box.height/590);
 CITIES.forEach(c=>{
  const plannedStop=plan&&routeStops(...plan).includes(c.id),connected=state.routes.some(r=>r.a===c.id||r.b===c.id);
  const city=state.cities[c.id],destination=selected&&DESTINATIONS[selected]===c.id,pressure=f.cityQueues[c.id]>city.queue;
  const g=node('g',{class:`city ${selected===c.id?'selected':''} ${destination?'destination':''} ${pressure?'under-pressure':''} ${plannedStop?'planned-stop':''} ${connected?'connected':''}`,transform:`translate(${c.x} ${c.y}) scale(1 ${verticalFix})`,role:'button',tabindex:0,'aria-label':`${c.name}: ${city.queue} waiting for ${name(DESTINATIONS[c.id])}, ${demand(state,c.id)} more this season, ${f.byCity[c.id]} forecast to arrive`});
  g.append(node('circle',{r:25,class:'hit'}));if(city.level>=1)for(let j=0;j<Math.floor(city.level)+1;j++)g.append(node('rect',{x:-16+j*7,y:-21-j%2*4,width:5,height:8+j%2*4,class:'growth'}));
  if(selected===c.id||destination)g.append(node('circle',{r:17,class:'selection'}));
  g.append(node('circle',{r:9,class:'halo'}),node('circle',{r:3,fill:selected===c.id?'#fff7df':'#365a4c'}));
  const right=c.x<290&&!['har','scr'].includes(c.id),x=right?15:-15,anchor=right?'start':'end';
  g.append(node('text',{x,y:0,'text-anchor':anchor,class:'city-name'},c.name),node('text',{x,y:13,'text-anchor':anchor,class:'city-demand'},`+${demand(state,c.id)} → ${short(DESTINATIONS[c.id])}`));
  const badgeY=c.id==='har'?-12:12;
  if(city.queue)g.append(node('circle',{cx:6,cy:badgeY,r:7,fill:pressure?'#a94f38':'#567563'}),node('text',{x:6,y:badgeY+3,class:'queue'},String(city.queue)));
  if(city.boom)g.append(node('text',{x:-16,y:4,fill:'#a96530','font-size':13},'✦'));
  g.onclick=()=>tapCity(c.id);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tapCity(c.id);}};$('cities').append(g);
 });
 $('hand').innerHTML=state.hand.map((key,i)=>`<button class="card ${targetCard===i?'active':''}" data-card="${i}" aria-label="${CARDS[key].name}: ${CARDS[key].description}" ${state.actions===0||state.status!=='playing'?'disabled':''}><span class="card-icon">${CARDS[key].icon}</span><span class="card-tag">${CARDS[key].tag}</span><strong>${CARDS[key].name}</strong><span class="card-desc">${CARDS[key].description}</span></button>`).join('');$('hand').querySelectorAll('button').forEach(b=>b.onclick=()=>cardModal(+b.dataset.card));
 $('route-plan').hidden=!selected;
 if(plan){
  const construction=routePlan(state,...plan),cost=construction.cost,impact=routeImpact(state,...plan),extra=impact.extraServed||0;
  const benefit=impact.error?impact.error:extra>0?`<b>${extra} more passengers reach their destination this season.</b>`:'<b>No extra arrivals this season.</b> This line does not solve a current journey or bottleneck.';
  const helped=impact.after?CITIES.filter(c=>impact.after.byCity[c.id]>impact.before.byCity[c.id]).map(c=>`${short(c.id)} → ${short(DESTINATIONS[c.id])}`).slice(0,2).join(' · '):'';
  const details=impact.after?`Queues: ${impact.before.waiting} → ${impact.after.waiting} · Income: ${signed(impact.before.income)} → ${signed(impact.after.income)}`:'';
  $('route-plan').innerHTML=`<div class="plan-title">${name(plan[0])} ↔ ${name(plan[1])}<span>${cost} funds · 1 action</span></div><div class="stop-list"><b>STOPS</b> ${construction.stops.map(short).join(' → ')}<span>${construction.newSegments.length} new segment${construction.newSegments.length===1?'':'s'}${construction.segments.length>construction.newSegments.length?' · existing track reused':''}</span></div><p class="route-impact">${benefit}</p><span class="plan-details">${helped?`Helps ${helped}. `:''}${details}</span><div class="plan-buttons"><button class="secondary" id="cancel-route">Cancel</button><button class="primary" id="build" ${impact.error||state.actions===0?'disabled':''}>Build · ${cost} funds</button></div>`;
  $('cancel-route').onclick=clearSelection;$('build').onclick=()=>{const error=buildRoute(state,...plan);if(error)msg(error);else{tone(600);msg(`Line opened with ${construction.stops.length} stops: ${extra} extra arrivals. ${impact.newConnections.length?'New journeys unlocked!':''}`);selected=null;plan=null;}render();};
 }else if(selected){
  const id=selected,path=findPath(state,id,DESTINATIONS[id]);
  $('route-plan').innerHTML=`<div class="plan-title">${name(id)} → ${name(DESTINATIONS[id])}<button id="clear-city" aria-label="Clear city selection">×</button></div><p class="route-impact"><b>${state.cities[id].queue} waiting + ${demand(state,id)} arriving this season.</b> ${f.byCity[id]} will reach their destination.</p><span class="plan-details">${path?`Journey: ${path.cities.map(short).join(' → ')}. ${f.cityQueues[id]>0?'Seats or station capacity are running short.':'This journey is covered.'}`:'No rail journey yet. Connect to the highlighted city, or use a connected city for a transfer.'}</span>`;
  $('clear-city').onclick=clearSelection;
 }
}
function clearSelection(){selected=null;plan=null;targetCard=null;msg('Tap a city to see where its passengers need to go.');render();}
function tapCity(id){if(state.status!=='playing'||state.challenge!==null)return;tone(360);
 if(targetCard!==null){const before=forecast(state),title=CARDS[state.hand[targetCard]].name,error=playCard(state,targetCard,id);if(error)msg(error);else{const after=forecast(state);msg(`${title}: ${after.served-before.served} extra arrivals forecast. New demand: ${demand(state,id)} / season.`);targetCard=null;selected=null;}render();return;}
 if(!selected||selected===id){selected=selected===id?null:id;plan=null;msg(selected?'Destination highlighted. Tap another city to preview a line and all its stops.':'Selection cleared. Choose a city to inspect its journeys.');}else if(state.actions===0){selected=id;plan=null;msg('No actions left. You can inspect cities, then end the season.');}else{plan=[selected,id];msg('Every listed stop will connect. Existing track is reused.');}render();
}
function tapRoute(i){const r=state.routes[i];if(targetCard!==null){const before=forecast(state),error=playCard(state,targetCard,i);if(error)msg(error);else{const after=forecast(state);targetCard=null;msg(`Express service: ${after.served-before.served} extra arrivals forecast · 1 fund upkeep.`);tone(650);}render();}else{const f=forecast(state);modal(`<span class="eyebrow">TRACK SEGMENT · SEASON ${state.turn}</span><h2>${name(r.a)} ↔ ${name(r.b)}</h2><p><b>${f.lineUsed[i]} of ${r.capacity} seats used this season</b>, shared by both directions and transferring passengers.</p><p>${f.lineUsed[i]===r.capacity?'This segment is full. An Express Line card or another route can relieve it.':'Spare seats remain. Check whether waiting passengers have a connected journey, or whether a station is full.'}</p><p>${f.deliveries.filter(d=>d.path.some((id,j)=>(id===r.a&&d.path[j+1]===r.b)||(id===r.b&&d.path[j+1]===r.a))).map(d=>`${short(d.from)} → ${short(d.to)}`).join(' · ')||'No completed journeys forecast on this line.'}</p><button class="primary" id="close-route">Back to the map</button>`);$('close-route').onclick=()=>$('modal').close();}}
function modal(html){$('modal').innerHTML=html;$('modal').showModal();}
function cardModal(i){const c=CARDS[state.hand[i]];modal(`<span class="eyebrow">${c.tag} · ONE ACTION</span><div class="medallion">${c.icon}</div><h2>${c.name}</h2><p>${c.description}</p><button class="primary" id="use-card">${c.target==='none'?'Play card':c.target==='city'?'Choose a city':'Choose a route'}</button><button class="secondary" id="close-modal">Keep in hand</button>`);$('close-modal').onclick=()=>{targetCard=null;$('modal').close();render();};$('use-card').onclick=()=>{$('modal').close();selected=null;plan=null;if(c.target==='none'){const error=playCard(state,i);msg(error||`${c.name} played. ${c.description}`);tone();}else{targetCard=i;msg(`Tap ${c.target==='city'?'a city':'a rail line'} for ${c.name}.`);}render();};}
function onboarding(){modal(`<span class="eyebrow">YOUR RAILWAY HAS A JOB TO DO</span><h2>Get people where<br>they need to go.</h2><p>Survive 24 seasons. <b>You lose at 160 waiting passengers</b> or if upkeep takes funds below zero.</p><ol><li><b>Read a city's journey.</b><span>“+2 → NYC” means two new passengers for New York each season. A number on the city is its current queue.</span></li><li><b>Connect their destinations.</b><span>Trains follow connected lines and can transfer. Long lines stop at cities along the corridor—the preview lists every stop. Each track segment has 6 seats per season. Existing track is reused; crossings alone are not stations.</span></li><li><b>Spend two actions wisely.</b><span>Preview any line: see extra arrivals, remaining queues, and income before building. Cards can improve full lines and crowded stations.</span></li><li><b>Keep the queues down.</b><span>Every 3 delivered passengers earn 1 fund; each arrival earns 5 prosperity. Demand rises at seasons 9 and 17, and growing cities attract more people.</span></li></ol><button class="primary" id="start">Find our first passengers</button>`);$('start').onclick=()=>{try{localStorage.setItem('atlas-onboarded-v3','1');}catch{}$('modal').close();};}
function dispatchModal(){const f=forecast(state),waiting=Object.values(state.cities).reduce((n,c)=>n+c.queue,0);
 const cityRows=[...CITIES].sort((a,b)=>f.cityQueues[b.id]-f.cityQueues[a.id]).map(c=>{const q=f.cityQueues[c.id];return `<li><b>${name(c.id)} → ${short(DESTINATIONS[c.id])}</b><span>${state.cities[c.id].queue} waiting + ${demand(state,c.id)} new − ${f.byCity[c.id]} delivered = <b>${q} left</b>. ${f.missing[c.id]?'No connected journey.':q>0?'A line or station is full.':'Journey covered.'}</span></li>`;}).join('');
 const bottlenecks=CITIES.filter(c=>f.stationUsed[c.id]===capacity(state,c.id)).map(c=>`${name(c.id)} station (${capacity(state,c.id)} / ${capacity(state,c.id)})`);
 modal(`<span class="eyebrow">SEASON ${state.turn} · DISPATCH FORECAST</span><h2>${f.waiting>=160?'Gridlock ahead.':'Every passenger counts.'}</h2><div class="dispatch-summary"><span><b>${f.arrivalCount}</b> new passengers</span><span><b>${f.served}</b> reach destination</span><span><b>${f.waiting}</b> still waiting</span></div><p>Queue: <b>${waiting} → ${f.waiting}</b>. You lose at <b>160 waiting</b>. ${f.disconnected} cannot reach their destination; ${f.capacityBlocked} have a journey but insufficient capacity.</p><p>Treasury: 3 subsidy + ${f.fares} fares + ${f.boomIncome} boom-town income − ${f.upkeep} upkeep = <b>${signed(f.income)} funds</b>. ${state.debt?`Bonds have ${state.debt} repayment seasons left.`:''}</p>${bottlenecks.length?`<p class="bottleneck"><b>Station bottlenecks:</b> ${bottlenecks.join(', ')}. Use Station Upgrade or route around the hub.</p>`:''}<ul class="journey-list">${cityRows}</ul><button class="primary" id="close-dispatch">Back to planning</button>`);$('close-dispatch').onclick=()=>$('modal').close();}
function challenge(){const q=CHALLENGES[state.challenge];if(!q)return;modal(`<span class="eyebrow">ATLAS CHALLENGE · ${q.type}</span><h2>${q.question}</h2><p>Correct answer: +4 funds and −1 waiting passenger per city. No penalty for a wrong answer.</p>${q.answers.map((a,i)=>`<button class="answer" data-answer="${i}">${a}</button>`).join('')}<button class="secondary" id="skip">Skip & keep building</button>`);$('modal').querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const result=answerChallenge(state,+b.dataset.answer);$('modal').innerHTML=`<span class="eyebrow">${result.correct?'WELL TRAVELLED':'A NOTE FROM THE ATLAS'}</span><h2>${result.correct?'A splendid answer.':'Something new to take along.'}</h2><p>${result.fact}</p><p>${result.correct?'You earned 4 funds. Every city’s queue fell by 1.':'No penalty. Your railway awaits.'}</p><button class="primary" id="resume">Return to the railway</button>`;$('resume').onclick=()=>{$('modal').close();render();};tone(result.correct?700:300);render();});$('skip').onclick=()=>{answerChallenge(state,-1);$('modal').close();render();msg('Challenge skipped. Check the forecast before sending trains.');};}
function ending(){modal(`<span class="eyebrow">THE RAILWAY GAZETTE · 1926</span><div class="medallion">${state.status==='won'?'✦':'╫'}</div><h2>${state.status==='won'?'A railway to remember.':state.status==='bankrupt'?'The treasury ran dry.':'The stations overflowed.'}</h2><p>${state.status==='won'?`You completed 24 seasons and delivered ${state.totalServed} passengers. ${state.lastReport.waiting} are still waiting—can your next railway do better?`:state.status==='bankrupt'?'Upkeep exceeded the treasury. Carry more passengers to earn fares, and take care with Express Lines and Civic Bonds.':'160 passengers were left waiting. Connect their actual destinations, then improve the lines and stations that run full.'}</p><div class="result-stats"><span><b>${state.score}</b> prosperity</span><span><b>${state.totalServed}</b> arrivals</span><span>Season <b>${state.turn}</b></span></div><button class="primary" id="restart">Begin a new journey</button><button class="secondary" id="view-map">Inspect the map</button>`);$('restart').onclick=()=>{$('modal').close();state=createGame();clearSelection();};$('view-map').onclick=()=>{$('modal').close();$('next').disabled=false;$('next').textContent='New journey';};}
$('next').onclick=()=>{if(state.status!=='playing'){state=createGame();clearSelection();return;}if(state.actions>0){const f=forecast(state);modal(`<span class="eyebrow">SEASON ${state.turn} · ${state.actions} UNUSED ACTION${state.actions===1?'':'S'}</span><h2>Send the trains?</h2><p><b>${f.served} passengers will arrive; ${f.waiting} will still be waiting.</b> Lose at 160. Treasury changes by ${signed(f.income)} funds.</p><p>Unused actions expire. Building a useful connection or upgrading a bottleneck can improve this forecast.</p><button class="primary" id="confirm-next">End season anyway</button><button class="secondary" id="stay">Keep planning</button>`);$('stay').onclick=()=>$('modal').close();$('confirm-next').onclick=()=>{$('modal').close();advance();};}else advance();};
function advance(){const before=state.congestion;endTurn(state);selected=null;plan=null;targetCard=null;tone(500);msg(`${state.lastReport.served} reached their destination. ${state.lastReport.waiting} waiting; congestion ${signed(state.congestion-before)}%.`);render();if(state.status!=='playing')ending();else if(state.challenge!==null)challenge();}
$('forecast').onclick=dispatchModal;$('help').onclick=onboarding;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♪':'♫';$('sound').setAttribute('aria-label',sound?'Disable sound':'Enable sound');tone();};$('modal').addEventListener('cancel',e=>{if(state.challenge!==null){e.preventDefault();return;}targetCard=null;render();});render();try{if(!localStorage.getItem('atlas-onboarded-v3'))onboarding();}catch{onboarding();}
window.atlas={snapshot:()=>structuredClone(state)};
window.addEventListener('resize',render);
