import {CITIES,CARDS,CHALLENGES,createGame,routeCost,capacity,demand,buildRoute,playCard,endTurn,answerChallenge} from './game.js';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';let state=createGame(),selected=null,plan=null,targetCard=null,sound=false,audio=null;
const name=id=>CITIES.find(c=>c.id===id).name;
function tone(freq=440){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.start();o.stop(audio.currentTime+.13);}catch{}}
function msg(text){$('message').textContent=text;}
function node(tag,attrs={},text){const el=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,v);if(text)el.textContent=text;return el;}
function render(){ $('season').innerHTML=`${String(state.turn).padStart(2,'0')} <small>/ 24</small>`;$('funds').innerHTML=`${state.funds} <small>funds</small>`;$('score').innerHTML=`${state.score} <small>pts</small>`;$('congestion-label').textContent=state.congestion+'%';$('congestion-bar').style.width=state.congestion+'%';$('actions').textContent=`${state.actions} action${state.actions===1?'':'s'} left`;$('next').disabled=state.status!=='playing'||state.challenge!==null;$('next').innerHTML=state.turn===24?'Finish railway →':'End season <span>→</span>';$('forecast').textContent=state.debt?`Bonds: 2 funds / season, ${state.debt} left.`:state.discount?`Next route: −${state.discount} funds.`:state.lastReport?`${state.lastReport.served} carried · +${state.lastReport.income} funds last season`:'Connect cities to carry passengers.';
$('routes').replaceChildren();state.routes.forEach((r,i)=>{const a=CITIES.find(c=>c.id===r.a),b=CITIES.find(c=>c.id===r.b);const attrs={x1:a.x,y1:a.y,x2:b.x,y2:b.y};$('routes').append(node('line',{...attrs,class:'rail-base'}),node('line',{...attrs,class:r.express?'rail express-rail':'rail'}));const hit=node('line',{...attrs,class:'route-hit',role:'button',tabindex:0,'aria-label':`${a.name} to ${b.name}, capacity ${r.capacity}`});hit.onclick=()=>tapRoute(i);hit.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tapRoute(i);}};$('routes').append(hit);const train=node('rect',{x:-5,y:-3,width:10,height:6,rx:2,class:'train'});if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const motion=node('animateMotion',{dur:`${4+i%3}s`,repeatCount:'indefinite',path:`M${a.x},${a.y} L${b.x},${b.y} L${a.x},${a.y}`,rotate:'auto'});train.append(motion);}else train.setAttribute('transform',`translate(${(a.x+b.x)/2} ${(a.y+b.y)/2})`);$('routes').append(train);});
$('cities').replaceChildren();CITIES.forEach(c=>{const city=state.cities[c.id],box=$('map').getBoundingClientRect(),verticalFix=(box.width/390)/(box.height/590),g=node('g',{class:`city ${selected===c.id?'selected':''}`,transform:`translate(${c.x} ${c.y}) scale(1 ${verticalFix})`,role:'button',tabindex:0,'aria-label':`${c.name}: ${city.queue} waiting, ${capacity(state,c.id)} capacity, ${demand(state,c.id)} demand per season`});g.append(node('circle',{r:25,class:'hit'}));if(city.level>=1)for(let j=0;j<Math.floor(city.level)+1;j++)g.append(node('rect',{x:-16+j*7,y:-19-j%2*4,width:5,height:8+j%2*4,class:'growth'}));if(selected===c.id)g.append(node('circle',{r:17,class:'selection'}));g.append(node('circle',{r:9,class:'halo'}),node('circle',{r:3,fill:selected===c.id?'#fff7df':'#365a4c'}));const right=c.x<290;g.append(node('text',{x:right?15:-15,y:4,'text-anchor':right?'start':'end',class:'city-name'},c.name));if(city.queue){g.append(node('circle',{cx:7,cy:12,r:7,fill:city.queue>12?'#a94f38':'#86714a'}),node('text',{x:7,y:15,class:'queue'},String(city.queue)));}if(city.boom)g.append(node('text',{x:-16,y:4,fill:'#a96530','font-size':13},'✦'));g.onclick=()=>tapCity(c.id);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tapCity(c.id);}};$('cities').append(g);});
$('hand').innerHTML=state.hand.map((key,i)=>`<button class="card ${targetCard===i?'active':''}" data-card="${i}" aria-label="${CARDS[key].name}: ${CARDS[key].description}" ${state.actions===0||state.status!=='playing'?'disabled':''}><span class="card-icon">${CARDS[key].icon}</span><span class="card-tag">${CARDS[key].tag}</span><strong>${CARDS[key].name}</strong><span class="card-desc">${CARDS[key].description}</span></button>`).join('');$('hand').querySelectorAll('button').forEach(b=>b.onclick=()=>cardModal(+b.dataset.card));$('route-plan').hidden=!plan;if(plan){const cost=routeCost(state,...plan);$('route-plan').innerHTML=`<strong>${name(plan[0])} ↔ ${name(plan[1])}</strong><br>${cost} funds · +${state.survey?4:3} capacity at each city · 1 action<div class="plan-buttons"><button class="secondary" id="cancel-route">Cancel</button><button class="primary" id="build" ${cost>state.funds||state.actions===0?'disabled':''}>Build railway</button></div>`;$('cancel-route').onclick=clearSelection;$('build').onclick=()=>{const error=buildRoute(state,...plan);if(error)msg(error);else{tone(600);msg(`Line opened! ${name(plan[0])} and ${name(plan[1])} are connected.`);selected=null;plan=null;}render();};}}
function clearSelection(){selected=null;plan=null;targetCard=null;msg('Tap a city, then another to plan a line.');render();}
function tapCity(id){if(state.status!=='playing'||state.challenge!==null)return;tone(360);if(targetCard!==null){const title=CARDS[state.hand[targetCard]].name,error=playCard(state,targetCard,id);if(error)msg(error);else{msg(`${title} applied to ${name(id)}.`);targetCard=null;selected=null;}render();return;}if(state.actions===0){msg('Your crews are finished. End the season to gain 2 actions.');return;}if(!selected||selected===id){selected=selected===id?null:id;plan=null;msg(selected?`${name(id)}: ${state.cities[id].queue} waiting · ${capacity(state,id)} capacity. Tap a second city.`:'Selection cleared. Tap any city to begin.');}else{plan=[selected,id];msg('Review your new line, then build.');}render();}
function tapRoute(i){if(targetCard!==null){const error=playCard(state,targetCard,i);if(error)msg(error);else{targetCard=null;msg('Express service opened. +3 capacity at both stations; 1 fund upkeep.');tone(650);}render();}else{const r=state.routes[i];msg(`${name(r.a)} ↔ ${name(r.b)} · ${r.capacity} capacity${r.express?' · 1 fund upkeep':''}.`);}}
function modal(html){$('modal').innerHTML=html;$('modal').showModal();}
function cardModal(i){const c=CARDS[state.hand[i]];modal(`<span class="eyebrow">${c.tag} · ONE ACTION</span><div class="medallion">${c.icon}</div><h2>${c.name}</h2><p>${c.description}</p><button class="primary" id="use-card">${c.target==='none'?'Play card':c.target==='city'?'Choose a city':'Choose a route'}</button><button class="secondary" id="close-modal">Keep in hand</button>`);$('close-modal').onclick=()=>{targetCard=null;$('modal').close();render();};$('use-card').onclick=()=>{$('modal').close();selected=null;plan=null;if(c.target==='none'){const error=playCard(state,i);msg(error||`${c.name} played. ${c.description}`);tone();}else{targetCard=i;msg(`Tap ${c.target==='city'?'a city':'an existing rail line'} for ${c.name}. Tap the card to change your mind.`);}render();};}
function onboarding(){modal(`<span class="eyebrow">WELCOME, RAILWAY DIRECTOR</span><h2>A little railway.<br>A growing world.</h2><p>Build a thriving Northeast network in 24 seasons. Take your time: a journey lasts about 10–15 minutes.</p><ol><li><b>Connect cities.</b><span>Tap two city dots, then build. Routes cost funds and one of your two actions.</span></li><li><b>Keep up with demand.</b><span>Each season brings passengers. Rail capacity serves both endpoints; waiting passengers cause congestion.</span></li><li><b>Use your three cards.</b><span>Each costs an action. Read the tradeoffs before you play.</span></li><li><b>Survive the final season.</b><span>Reach season 24 before congestion hits 100%. Optional trivia earns funds and reduces queues.</span></li></ol><button class="primary" id="start">Let’s lay some tracks</button>`);$('start').onclick=()=>{try{localStorage.setItem('atlas-onboarded','1');}catch{}$('modal').close();};}
function challenge(){const q=CHALLENGES[state.challenge];if(!q)return;modal(`<span class="eyebrow">ATLAS CHALLENGE · ${q.type}</span><h2>${q.question}</h2><p>Correct answer: +4 funds and −1 waiting passenger per city. No penalty for a wrong answer.</p>${q.answers.map((a,i)=>`<button class="answer" data-answer="${i}">${a}</button>`).join('')}<button class="secondary" id="skip">Skip & keep building</button>`);$('modal').querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const result=answerChallenge(state,+b.dataset.answer);$('modal').innerHTML=`<span class="eyebrow">${result.correct?'WELL TRAVELLED':'A NOTE FROM THE ATLAS'}</span><h2>${result.correct?'A splendid answer.':'Something new to take along.'}</h2><p>${result.fact}</p><p>${result.correct?'You earned 4 funds. Every city’s queue fell by 1.':'No penalty. Your railway awaits.'}</p><button class="primary" id="resume">Return to the railway</button>`;$('resume').onclick=()=>{$('modal').close();render();};tone(result.correct?700:300);render();});$('skip').onclick=()=>{answerChallenge(state,-1);$('modal').close();render();msg('Challenge skipped. Your crews are ready.');};}
function ending(){modal(`<span class="eyebrow">THE RAILWAY GAZETTE · 1926</span><div class="medallion">${state.status==='won'?'✦':'╫'}</div><h2>${state.status==='won'?'A railway to remember.':'The stations overflowed.'}</h2><p>${state.status==='won'?'Your network carried the Northeast through all 24 seasons. The cities salute you.':'Congestion reached 100%. Connect isolated towns earlier, and upgrade busy stations before demand grows.'}</p><div class="result-stats"><span><b>${state.score}</b> prosperity</span><span><b>${state.routes.length}</b> rail lines</span><span>Season <b>${state.turn}</b></span></div><button class="primary" id="restart">Begin a new journey</button><button class="secondary" id="view-map">Admire the map</button>`);$('restart').onclick=()=>{$('modal').close();state=createGame();clearSelection();};$('view-map').onclick=()=>{$('modal').close();$('next').disabled=false;$('next').textContent='New journey';};}
$('next').onclick=()=>{if(state.status!=='playing'){state=createGame();clearSelection();return;}if(state.actions>0){modal(`<span class="eyebrow">SEASON ${state.turn}</span><h2>Send the trains?</h2><p>You have ${state.actions} unused action${state.actions===1?'':'s'}. Ending the season carries passengers, collects income, and adds new demand.</p><button class="primary" id="confirm-next">End season anyway</button><button class="secondary" id="stay">Keep building</button>`);$('stay').onclick=()=>$('modal').close();$('confirm-next').onclick=()=>{$('modal').close();advance();};}else advance();};
function advance(){endTurn(state);selected=null;plan=null;targetCard=null;tone(500);msg(`${state.lastReport.served} passengers carried. ${state.lastReport.waiting} waiting. Demand ${state.turn===7||state.turn===13||state.turn===19?'has grown!':'continues to grow.'}`);render();if(state.status!=='playing')ending();else if(state.challenge!==null)challenge();}
$('help').onclick=onboarding;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♪':'♫';$('sound').setAttribute('aria-label',sound?'Disable sound':'Enable sound');tone();};$('modal').addEventListener('cancel',e=>{if(state.challenge!==null){e.preventDefault();return;}targetCard=null;render();});render();try{if(!localStorage.getItem('atlas-onboarded'))onboarding();}catch{onboarding();}
// Read-only snapshot for browser QA; mutations go through the game engine.
window.atlas={snapshot:()=>structuredClone(state)};

window.addEventListener('resize',render);
