export const CITIES = [
{id:'buf',name:'Buffalo',x:66,y:119,lat:42.89,lon:-78.87},{id:'alb',name:'Albany',x:222,y:143,lat:42.65,lon:-73.75},{id:'bos',name:'Boston',x:337,y:183,lat:42.36,lon:-71.06},{id:'scr',name:'Scranton',x:145,y:257,lat:41.41,lon:-75.66},{id:'har',name:'Hartford',x:259,y:231,lat:41.76,lon:-72.67},{id:'pro',name:'Providence',x:331,y:264,lat:41.82,lon:-71.41},{id:'nyc',name:'New York',x:237,y:328,lat:40.71,lon:-74.01},{id:'phi',name:'Philadelphia',x:171,y:398,lat:39.95,lon:-75.17},{id:'bal',name:'Baltimore',x:117,y:470,lat:39.29,lon:-76.61},{id:'dc',name:'Washington DC',x:76,y:529,lat:38.91,lon:-77.04}];
export const CARDS={grant:{name:'Rail Grant',icon:'▤',tag:'PUBLIC WORKS',description:'Your next route costs 4 less. Its stations gain 2 waiting passengers each.',target:'none'},station:{name:'Station Upgrade',icon:'⌂',tag:'INFRASTRUCTURE',description:'Pay 4 funds: +3 capacity at one city. New facilities attract +1 demand each season.',target:'city'},express:{name:'Express Line',icon:'➟',tag:'OPERATIONS',description:'Pay 3 funds: +3 capacity at both ends of a route. Costs 1 fund every season.',target:'route'},boom:{name:'Boom Town',icon:'✦',tag:'DEVELOPMENT',description:'One city earns +2 funds each season, but adds +2 demand. Connect it first!',target:'city'},survey:{name:'Survey Crew',icon:'⌖',tag:'PLANNING',description:'Your next route costs 2 less and adds +1 capacity at both ends. Uses an action.',target:'none'},bonds:{name:'Civic Bonds',icon:'◈',tag:'FINANCE',description:'Receive 8 funds now. Repay 2 each season for the next 5 seasons.',target:'none'}};
const deck=['grant','station','bonds','express','boom','survey'];
export const CHALLENGES=[
{type:'GEOGRAPHY',question:'Which of these cities lies farthest west?',answers:['Buffalo','Albany','Scranton'],correct:0,fact:'Buffalo sits on Lake Erie, at the western edge of New York.'},
{type:'HISTORICAL GEOGRAPHY',question:'Which city was the U.S. capital from 1790 to 1800?',answers:['Boston','Philadelphia','Baltimore'],correct:1,fact:'Philadelphia served as the capital before the government moved to Washington.'},
{type:'WORD PUZZLE',question:'Unscramble “NOSTOB” to find a city on your map.',answers:['Boston','Buffalo','Albany'],correct:0,fact:'Boston! A coastal hub with a long history of trade and rail travel.'},
{type:'CAPITALS & CITIES',question:'What is the capital of New York State?',answers:['New York City','Buffalo','Albany'],correct:2,fact:'Albany has been New York’s state capital since 1797.'},
{type:'HISTORY',question:'The Declaration of Independence was adopted in which city?',answers:['Washington DC','Philadelphia','Providence'],correct:1,fact:'The Continental Congress adopted it in Philadelphia on July 4, 1776.'},
{type:'GEOGRAPHY',question:'Which bay meets the Atlantic near Baltimore?',answers:['Chesapeake Bay','San Francisco Bay','Hudson Bay'],correct:0,fact:'Baltimore’s harbor connects to the Chesapeake Bay via the Patapsco River.'}];
export function createGame(seed=1920){return {seed,turn:1,actions:2,funds:18,score:0,congestion:0,routes:[],cities:Object.fromEntries(CITIES.map(c=>[c.id,{queue:1,level:0,upgrade:0,boom:false}])),hand:['grant','station','bonds'],draw:3,discount:0,survey:false,debt:0,status:'playing',challenge:null,challengeDone:0,lastReport:null};}
export function routeCost(s,a,b){const A=CITIES.find(c=>c.id===a),B=CITIES.find(c=>c.id===b);if(!A||!B)return Infinity;const km=Math.hypot((A.lon-B.lon)*82,(A.lat-B.lat)*111);return Math.max(2,Math.ceil(km/65)+2-s.discount);}
export function capacity(s,id){return s.routes.reduce((n,r)=>n+(r.a===id||r.b===id?r.capacity:0),0)+s.cities[id].upgrade*3;}
export function demand(s,id){const i=CITIES.findIndex(c=>c.id===id);return 1+(i===6||i===2?1:0)+Math.floor((s.turn-1)/6)+Math.floor(s.cities[id].level)+s.cities[id].upgrade+(s.cities[id].boom?2:0);}
function available(s){return s.status==='playing'&&!s.challenge&&s.actions>0;}
export function buildRoute(s,a,b){if(!available(s))return 'No actions left. Advance the season.';if(!s.cities[a]||!s.cities[b]||a===b)return 'Choose two different cities.';if(s.routes.some(r=>(r.a===a&&r.b===b)||(r.a===b&&r.b===a)))return 'These cities are already connected.';const cost=routeCost(s,a,b);if(s.funds<cost)return `You need ${cost} funds for this route.`;s.funds-=cost;s.actions--;s.routes.push({a,b,capacity:3+(s.survey?1:0),express:false});if(s.discount===4){s.cities[a].queue+=2;s.cities[b].queue+=2;}s.discount=0;s.survey=false;s.score+=5;return null;}
export function playCard(s,index,target){if(!available(s))return 'Advance the season to gain more actions.';const key=s.hand[index],card=CARDS[key];if(!card)return 'Card unavailable.';if(card.target==='city'&&!s.cities[target])return 'Choose a city on the map.';if(key==='station'&&s.funds<4)return 'Station upgrade needs 4 funds.';if(key==='express'){const r=s.routes[target];if(!r)return 'Choose an existing rail route.';if(r.express)return 'This route is already express.';if(s.funds<3)return 'Express line needs 3 funds.';r.capacity+=3;r.express=true;s.funds-=3;}
if(key==='grant'||key==='survey'){if(s.discount)return 'Build your discounted route first.';s.discount=key==='grant'?4:2;s.survey=key==='survey';}
if(key==='station'){s.funds-=4;s.cities[target].upgrade++;}
if(key==='boom'){if(s.cities[target].boom)return 'This city is already booming.';s.cities[target].boom=true;}
if(key==='bonds'){if(s.debt)return 'Repay your current bonds first.';s.funds+=8;s.debt=5;}
s.actions--;s.hand[index]=deck[(s.draw++ + s.seed%6)%deck.length];return null;}
export function endTurn(s){if(s.status!=='playing'||s.challenge)return false;let served=0,income=5,waiting=0;for(const c of CITIES){const city=s.cities[c.id];city.queue+=demand(s,c.id);const moved=Math.min(city.queue,capacity(s,c.id));city.queue-=moved;served+=moved;waiting+=city.queue;if(moved){income+=1+(city.boom?2:0);city.level=Math.min(3,city.level+0.2);}}
const upkeep=s.routes.filter(r=>r.express).length+(s.debt?2:0);if(s.debt)s.debt--;s.funds+=income-upkeep;s.score+=served;s.congestion=Math.min(100,Math.round(waiting/1.6));s.lastReport={served,income:income-upkeep,waiting};if(s.congestion>=100)s.status='lost';else if(s.turn===24)s.status='won';else{s.turn++;s.actions=2;if((s.turn-1)%4===0)s.challenge=Math.floor((s.turn-1)/4)-1;}return true;}
export function answerChallenge(s,answer){if(s.challenge===null)return null;const q=CHALLENGES[s.challenge];const correct=answer===q.correct;if(correct){s.funds+=4;for(const c of Object.values(s.cities))c.queue=Math.max(0,c.queue-1);s.congestion=Math.min(100,Math.round(Object.values(s.cities).reduce((n,c)=>n+c.queue,0)/1.6));}s.challenge=null;s.challengeDone++;return {correct,fact:q.fact};}
